import { ConsoleOption } from "@/types";

/**
 * Media types configuration for ESDE
 */
export const MEDIA_TYPES = [
  {
    key: "covers",
    folder: "covers",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Cover Image",
    description: "Main cover art for the game",
  },
  {
    key: "marquees",
    folder: "marquees",
    extension: ".png",
    accept: "image/png",
    label: "Marquee (Logo)",
    description: "Game logo, usually transparent PNG",
  },
  {
    key: "videos",
    folder: "videos",
    extension: ".mp4",
    accept: "video/mp4",
    label: "Video",
    description: "Gameplay video or trailer",
  },
  {
    key: "3dboxes",
    folder: "3dboxes",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "3D Box",
    description: "3D render of the game box",
  },
  {
    key: "backcovers",
    folder: "backcovers",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Back Cover",
    description: "Back of the box art",
  },
  {
    key: "fanart",
    folder: "fanart",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Fan Art",
    description: "Fan-created artwork for the game",
  },

  {
    key: "physicalmedia",
    folder: "physicalmedia",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Physical Media",
    description: "Image of the actual physical media (cartridge, disc, etc.)",
  },
  {
    key: "screenshots",
    folder: "screenshots",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Screenshot",
    description: "In-game screenshot",
  },
  {
    key: "titlescreens",
    folder: "titlescreens",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Title Screen",
    description: "Game title screen or menu",
  },
];

/**
 * List of supported console systems
 */
export const CONSOLES: ConsoleOption[] = [
  { value: "3do", label: "3DO" },
  { value: "adam", label: "Coleco Adam" },
  { value: "ags", label: "Adventure Game Studio" },
  { value: "amiga", label: "Amiga" },
  { value: "amiga1200", label: "Amiga 1200" },
  { value: "amiga600", label: "Amiga 600" },
  { value: "amigacd32", label: "Amiga CD32" },
  { value: "amstradcpc", label: "Amstrad CPC" },
  { value: "apple2", label: "Apple II" },
  { value: "apple2gs", label: "Apple IIGS" },
  { value: "arcade", label: "Arcade" },
  { value: "arcadia", label: "Arcadia" },
  { value: "archimedes", label: "Archimedes" },
  { value: "arduboy", label: "Arduboy" },
  { value: "astrocde", label: "Astrocade" },
  { value: "atari2600", label: "Atari 2600" },
  { value: "atari5200", label: "Atari 5200" },
  { value: "atari7800", label: "Atari 7800" },
  { value: "atari800", label: "Atari 800" },
  { value: "atarijaguar", label: "Atari Jaguar" },
  { value: "atarilynx", label: "Atari Lynx" },
  { value: "atarist", label: "Atari ST" },
  { value: "atarixe", label: "Atari XE" },
  { value: "atomiswave", label: "Atomiswave" },
  { value: "bbcmicro", label: "BBC Micro" },
  { value: "c64", label: "Commodore 64" },
  { value: "cdimono1", label: "CD-i" },
  { value: "cdtv", label: "CDTV" },
  { value: "channelf", label: "Channel F" },
  { value: "coco", label: "Color Computer" },
  { value: "colecovision", label: "ColecoVision" },
  { value: "cps1", label: "CPS1" },
  { value: "cps2", label: "CPS2" },
  { value: "cps3", label: "CPS3" },
  { value: "dreamcast", label: "Sega Dreamcast" },
  { value: "dos", label: "DOS" },
  { value: "famicom", label: "Famicom" },
  { value: "fds", label: "Famicom Disk System" },
  { value: "gamegear", label: "Game Gear" },
  { value: "gb", label: "Game Boy" },
  { value: "gba", label: "Game Boy Advance" },
  { value: "gbc", label: "Game Boy Color" },
  { value: "gc", label: "GameCube" },
  { value: "genesis", label: "Genesis" },
  { value: "intellivision", label: "Intellivision" },
  { value: "mastersystem", label: "Master System" },
  { value: "megacd", label: "Mega CD" },
  { value: "megadrive", label: "Mega Drive" },
  { value: "msx", label: "MSX" },
  { value: "msx2", label: "MSX2" },
  { value: "n3ds", label: "Nintendo 3DS" },
  { value: "n64", label: "Nintendo 64" },
  { value: "n64dd", label: "Nintendo 64DD" },
  { value: "nds", label: "Nintendo DS" },
  { value: "neogeo", label: "Neo Geo" },
  { value: "neogeocd", label: "Neo Geo CD" },
  { value: "nes", label: "Nintendo Entertainment System" },
  { value: "ngp", label: "Neo Geo Pocket" },
  { value: "ngpc", label: "Neo Geo Pocket Color" },
  { value: "pcengine", label: "PC Engine" },
  { value: "pcenginecd", label: "PC Engine CD" },
  { value: "pcfx", label: "PC-FX" },
  { value: "ps2", label: "PlayStation 2" },
  { value: "ps3", label: "PlayStation 3" },
  { value: "ps4", label: "PlayStation 4" },
  { value: "psp", label: "PlayStation Portable" },
  { value: "psvita", label: "PlayStation Vita" },
  { value: "psx", label: "PlayStation" },
  { value: "saturn", label: "Sega Saturn" },
  { value: "saturnjp", label: "Sega Saturn (Japan)" },
  { value: "sega32x", label: "Sega 32X" },
  { value: "segacd", label: "Sega CD" },
  { value: "sg-1000", label: "SG-1000" },
  { value: "snes", label: "Super Nintendo" },
  { value: "switch", label: "Nintendo Switch" },
  { value: "tg16", label: "TurboGrafx-16" },
  { value: "tg-cd", label: "TurboGrafx-CD" },
  { value: "virtualboy", label: "Virtual Boy" },
  { value: "wii", label: "Nintendo Wii" },
  { value: "wiiu", label: "Nintendo Wii U" },
  { value: "wonderswan", label: "WonderSwan" },
  { value: "wonderswancolor", label: "WonderSwan Color" },
  { value: "xbox", label: "Xbox" },
  { value: "xbox360", label: "Xbox 360" },
  { value: "xboxone", label: "Xbox One" },
  { value: "zxspectrum", label: "ZX Spectrum" },
];

/**
 * Media filter options for filtering games by missing media types
 */
export const MEDIA_FILTER_OPTIONS = [
  {
    key: "all",
    label: "All Games",
    description: "Show all games regardless of media status",
  },
  {
    key: "missing-covers",
    label: "Missing Covers",
    description: "Show games that don't have cover images",
  },
  {
    key: "missing-marquees",
    label: "Missing Marquees/Logos",
    description: "Show games that don't have marquee/logo images",
  },
  {
    key: "missing-screenshots",
    label: "Missing Screenshots",
    description: "Show games that don't have screenshot images",
  },
  {
    key: "missing-titlescreens",
    label: "Missing Title Screens",
    description: "Show games that don't have title screen images",
  },
  {
    key: "missing-3dboxes",
    label: "Missing 3D Boxes",
    description: "Show games that don't have 3D box images",
  },
  {
    key: "missing-backcovers",
    label: "Missing Back Covers",
    description: "Show games that don't have back cover images",
  },
  {
    key: "missing-fanart",
    label: "Missing Fan Art",
    description: "Show games that don't have fan art images",
  },
  {
    key: "missing-physicalmedia",
    label: "Missing Physical Media",
    description: "Show games that don't have physical media images",
  },
  {
    key: "missing-videos",
    label: "Missing Videos",
    description: "Show games that don't have video files",
  },
  {
    key: "missing-any",
    label: "Missing Any Media",
    description: "Show games that are missing at least one media type",
  },
  {
    key: "complete",
    label: "Complete Media Sets",
    description: "Show games that have all media types available",
  },
];

/**
 * Quick filter options for one-click filtering shortcuts
 */
export const QUICK_FILTER_OPTIONS = [
  {
    key: "missing-any",
    label: "Missing Media",
    description: "Games missing at least one media type",
  },
  {
    key: "complete",
    label: "Complete",
    description: "Games with all media types",
  },
  {
    key: "has-videos",
    label: "Has Videos",
    description: "Games with video files",
  },
  {
    key: "missing-videos",
    label: "No Videos",
    description: "Games without video files",
  },
  {
    key: "missing-covers",
    label: "No Covers",
    description: "Games without cover images",
  },
  {
    key: "missing-marquees",
    label: "No Marquees",
    description: "Games without marquee/logo images",
  },
  {
    key: "missing-screenshots",
    label: "No Screenshots",
    description: "Games without screenshot images",
  },
  {
    key: "missing-titlescreens",
    label: "No Title Screens",
    description: "Games without title screen images",
  },
  {
    key: "missing-3dboxes",
    label: "No 3D Boxes",
    description: "Games without 3D box images",
  },
  {
    key: "missing-backcovers",
    label: "No Back Covers",
    description: "Games without back cover images",
  },
  {
    key: "missing-fanart",
    label: "No Fan Art",
    description: "Games without fan art images",
  },
  {
    key: "missing-physicalmedia",
    label: "No Physical Media",
    description: "Games without physical media images",
  },
];
