import { ConsoleOption } from "@/types";

/**
 * Media types configuration for ESDE
 */
export const MEDIA_TYPES = [
  {
    key: "covers",
    folder: "covers",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Cover Image",
    description: "Main cover art for the game",
  },
  {
    key: "marquees",
    folder: "marquees",
    extension: ".png",
    accept: "image/png",
    label: "Marquee (Logo)",
    description: "Game logo, usually transparent PNG",
  },
  {
    key: "videos",
    folder: "videos",
    extension: ".mp4",
    accept: "video/mp4",
    label: "Video",
    description: "Gameplay video or trailer",
  },
  {
    key: "3dboxes",
    folder: "3dboxes",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "3D Box",
    description: "3D render of the game box",
  },
  {
    key: "backcovers",
    folder: "backcovers",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Back Cover",
    description: "Back of the box art",
  },
  {
    key: "fanart",
    folder: "fanart",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Fan Art",
    description: "Fan-created artwork for the game",
  },

  {
    key: "physicalmedia",
    folder: "physicalmedia",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Physical Media",
    description: "Image of the actual physical media (cartridge, disc, etc.)",
  },
  {
    key: "screenshots",
    folder: "screenshots",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Screenshot",
    description: "In-game screenshot",
  },
  {
    key: "titlescreens",
    folder: "titlescreens",
    extension: ".jpg",
    accept: "image/jpeg",
    label: "Title Screen",
    description: "Game title screen or menu",
  },
];

/**
 * List of supported console systems (based on ES-DE 3.3.0 official documentation)
 * Source: https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#supported-game-systems
 * Updated: 2025-01-24
 *
 * This comprehensive list includes all game systems supported by ES-DE 3.3.0.
 * System names correspond to the directory names where game files should be placed. (based on ES-DE 3.3.0 official documentation)
 */
export const CONSOLES: ConsoleOption[] = [
  { value: "3do", label: "3DO Interactive Multiplayer" },
  { value: "adam", label: "Coleco Adam" },
  { value: "ags", label: "Adventure Game Studio" },
  { value: "amiga", label: "Commodore Amiga" },
  { value: "amiga1200", label: "Commodore Amiga 1200" },
  { value: "amiga600", label: "Commodore Amiga 600" },
  { value: "amigacd32", label: "Commodore Amiga CD32" },
  { value: "amstradcpc", label: "Amstrad CPC" },
  { value: "android", label: "Google Android" },
  { value: "androidapps", label: "Android Apps" },
  { value: "androidgames", label: "Android Games" },
  { value: "apple2", label: "Apple II" },
  { value: "apple2gs", label: "Apple IIGS" },
  { value: "arcade", label: "Arcade" },
  { value: "arcadia", label: "Emerson Arcadia 2001" },
  { value: "archimedes", label: "Acorn Archimedes" },
  { value: "arduboy", label: "Arduboy Miniature Game System" },
  { value: "astrocde", label: "Bally Astrocade" },
  { value: "atari2600", label: "Atari 2600" },
  { value: "atari5200", label: "Atari 5200" },
  { value: "atari7800", label: "Atari 7800 ProSystem" },
  { value: "atari800", label: "Atari 800" },
  { value: "atarijaguar", label: "Atari Jaguar" },
  { value: "atarijaguarcd", label: "Atari Jaguar CD" },
  { value: "atarilynx", label: "Atari Lynx" },
  { value: "atarist", label: "Atari ST" },
  { value: "atarixe", label: "Atari XE" },
  { value: "atomiswave", label: "Sammy Corporation Atomiswave" },
  { value: "bbcmicro", label: "Acorn Computers BBC Micro" },
  { value: "c64", label: "Commodore 64" },
  { value: "cdimono1", label: "Philips CD-i" },
  { value: "cdtv", label: "Commodore CDTV" },
  { value: "chailove", label: "ChaiLove Game Engine" },
  { value: "channelf", label: "Fairchild Channel F" },
  { value: "coco", label: "Tandy Color Computer" },
  { value: "colecovision", label: "Coleco ColecoVision" },
  { value: "consolearcade", label: "Console Arcade Systems" },
  { value: "cps", label: "Capcom Play System" },
  { value: "cps1", label: "Capcom Play System I" },
  { value: "cps2", label: "Capcom Play System II" },
  { value: "cps3", label: "Capcom Play System III" },
  { value: "crvision", label: "VTech CreatiVision" },
  { value: "daphne", label: "Daphne Arcade LaserDisc Emulator" },
  { value: "desktop", label: "Desktop Applications" },
  { value: "doom", label: "Doom" },
  { value: "dos", label: "DOS (PC)" },
  { value: "dragon32", label: "Dragon Data Dragon 32" },
  { value: "dreamcast", label: "Sega Dreamcast" },
  { value: "easyrpg", label: "EasyRPG Game Engine" },
  { value: "electron", label: "Acorn Electron" },
  { value: "emulators", label: "Emulators" },
  { value: "epic", label: "Epic Games Store" },
  { value: "famicom", label: "Nintendo Family Computer" },
  { value: "fba", label: "FinalBurn Alpha" },
  { value: "fbneo", label: "FinalBurn Neo" },
  { value: "fds", label: "Nintendo Famicom Disk System" },
  { value: "flash", label: "Adobe Flash" },
  { value: "fm7", label: "Fujitsu FM-7" },
  { value: "fmtowns", label: "Fujitsu FM Towns" },
  { value: "fpinball", label: "Future Pinball" },
  { value: "gamate", label: "Bit Corporation Gamate" },
  { value: "gameandwatch", label: "Nintendo Game and Watch" },
  { value: "gamecom", label: "Tiger Electronics Game.com" },
  { value: "gamegear", label: "Sega Game Gear" },
  { value: "gb", label: "Nintendo Game Boy" },
  { value: "gba", label: "Nintendo Game Boy Advance" },
  { value: "gbc", label: "Nintendo Game Boy Color" },
  { value: "gc", label: "Nintendo GameCube" },
  { value: "genesis", label: "Sega Genesis" },
  { value: "gmaster", label: "Hartung Game Master" },
  { value: "gx4000", label: "Amstrad GX4000" },
  { value: "intellivision", label: "Mattel Electronics Intellivision" },
  { value: "j2me", label: "Java 2 Micro Edition (J2ME)" },
  { value: "kodi", label: "Kodi Home Theatre Software" },
  { value: "laserdisc", label: "LaserDisc Games" },
  { value: "lcdgames", label: "LCD Handheld Games" },
  { value: "lowresnx", label: "LowRes NX Fantasy Console" },
  { value: "lutris", label: "Lutris Open Gaming Platform" },
  { value: "lutro", label: "Lutro Game Engine" },
  { value: "macintosh", label: "Apple Macintosh" },
  { value: "mame", label: "Multiple Arcade Machine Emulator" },
  { value: "mame-advmame", label: "AdvanceMAME" },
  { value: "mark3", label: "Sega Mark III" },
  { value: "mastersystem", label: "Sega Master System" },
  { value: "megacd", label: "Sega Mega-CD" },
  { value: "megacdjp", label: "Sega Mega-CD [Japan]" },
  { value: "megadrive", label: "Sega Mega Drive" },
  { value: "megadrivejp", label: "Sega Mega Drive [Japan]" },
  { value: "megaduck", label: "Creatronic Mega Duck" },
  { value: "mess", label: "Multi Emulator Super System" },
  { value: "model2", label: "Sega Model 2" },
  { value: "model3", label: "Sega Model 3" },
  { value: "moto", label: "Thomson MO/TO Series" },
  { value: "msx", label: "MSX" },
  { value: "msx1", label: "MSX1" },
  { value: "msx2", label: "MSX2" },
  { value: "msxturbor", label: "MSX Turbo R" },
  { value: "mugen", label: "M.U.G.E.N Game Engine" },
  { value: "multivision", label: "Othello Multivision" },
  { value: "n3ds", label: "Nintendo 3DS" },
  { value: "n64", label: "Nintendo 64" },
  { value: "n64dd", label: "Nintendo 64DD" },
  { value: "naomi", label: "Sega NAOMI" },
  { value: "naomi2", label: "Sega NAOMI 2" },
  { value: "naomigd", label: "Sega NAOMI GD-ROM" },
  { value: "nds", label: "Nintendo DS" },
  { value: "neogeo", label: "SNK Neo Geo" },
  { value: "neogeocd", label: "SNK Neo Geo CD" },
  { value: "neogeocdjp", label: "SNK Neo Geo CD [Japan]" },
  { value: "nes", label: "Nintendo Entertainment System" },
  { value: "ngage", label: "Nokia N-Gage" },
  { value: "ngp", label: "SNK Neo Geo Pocket" },
  { value: "ngpc", label: "SNK Neo Geo Pocket Color" },
  { value: "odyssey2", label: "Magnavox Odyssey 2" },
  { value: "openbor", label: "OpenBOR Game Engine" },
  { value: "oric", label: "Tangerine Computer Systems Oric" },
  { value: "palm", label: "Palm OS" },
  { value: "pc", label: "IBM PC" },
  { value: "pc88", label: "NEC PC-8800 Series" },
  { value: "pc98", label: "NEC PC-9800 Series" },
  { value: "pcarcade", label: "PC Arcade Systems" },
  { value: "pcengine", label: "NEC PC Engine" },
  { value: "pcenginecd", label: "NEC PC Engine CD" },
  { value: "pcfx", label: "NEC PC-FX" },
  { value: "pico8", label: "PICO-8 Fantasy Console" },
  { value: "plus4", label: "Commodore Plus/4" },
  { value: "pokemini", label: "Nintendo Pokémon Mini" },
  { value: "ports", label: "Ports" },
  { value: "ps2", label: "Sony PlayStation 2" },
  { value: "ps3", label: "Sony PlayStation 3" },
  { value: "ps4", label: "Sony PlayStation 4" },
  { value: "psp", label: "Sony PlayStation Portable" },
  { value: "psvita", label: "Sony PlayStation Vita" },
  { value: "psx", label: "Sony PlayStation" },
  { value: "pv1000", label: "Casio PV-1000" },
  { value: "quake", label: "Quake" },
  { value: "samcoupe", label: "MGT SAM Coupé" },
  { value: "satellaview", label: "Nintendo Satellaview" },
  { value: "saturn", label: "Sega Saturn" },
  { value: "saturnjp", label: "Sega Saturn [Japan]" },
  { value: "scummvm", label: "ScummVM Game Engine" },
  { value: "scv", label: "Epoch Super Cassette Vision" },
  { value: "sega32x", label: "Sega Mega Drive 32X" },
  { value: "sega32xjp", label: "Sega Super 32X [Japan]" },
  { value: "sega32xna", label: "Sega Genesis 32X [North America]" },
  { value: "segacd", label: "Sega CD" },
  { value: "sfc", label: "Nintendo SFC (Super Famicom)" },
  { value: "sg-1000", label: "Sega SG-1000" },
  { value: "sgb", label: "Nintendo Super Game Boy" },
  { value: "snes", label: "Nintendo SNES (Super Nintendo)" },
  { value: "snesna", label: "Nintendo SNES (Super Nintendo) [North America]" },
  { value: "solarus", label: "Solarus Game Engine" },
  { value: "spectravideo", label: "Spectravideo" },
  { value: "steam", label: "Valve Steam" },
  { value: "stv", label: "Sega Titan Video Game System" },
  { value: "sufami", label: "Bandai SuFami Turbo" },
  { value: "supergrafx", label: "NEC SuperGrafx" },
  { value: "supervision", label: "Watara Supervision" },
  { value: "supracan", label: "Funtech Super A'Can" },
  { value: "switch", label: "Nintendo Switch" },
  { value: "symbian", label: "Symbian" },
  { value: "tanodragon", label: "Tano Dragon" },
  { value: "tg16", label: "NEC TurboGrafx-16" },
  { value: "tg-cd", label: "NEC TurboGrafx-CD" },
  { value: "ti99", label: "Texas Instruments TI-99" },
  { value: "tic80", label: "TIC-80 Fantasy Computer" },
  { value: "to8", label: "Thomson TO8" },
  { value: "triforce", label: "Namco-Sega-Nintendo Triforce" },
  { value: "trs-80", label: "Tandy TRS-80" },
  { value: "type-x", label: "Taito Type X" },
  { value: "uzebox", label: "Uzebox Open Source Console" },
  { value: "vectrex", label: "GCE Vectrex" },
  { value: "vic20", label: "Commodore VIC-20" },
  { value: "videopac", label: "Philips Videopac G7000" },
  { value: "virtualboy", label: "Nintendo Virtual Boy" },
  { value: "vpinball", label: "Visual Pinball" },
  { value: "vsmile", label: "VTech V.Smile" },
  { value: "wasm4", label: "WASM-4 Fantasy Console" },
  { value: "wii", label: "Nintendo Wii" },
  { value: "wiiu", label: "Nintendo Wii U" },
  { value: "windows", label: "Microsoft Windows" },
  { value: "windows3x", label: "Microsoft Windows 3.x" },
  { value: "windows9x", label: "Microsoft Windows 9x" },
  { value: "wonderswan", label: "Bandai WonderSwan" },
  { value: "wonderswancolor", label: "Bandai WonderSwan Color" },
  { value: "x1", label: "Sharp X1" },
  { value: "x68000", label: "Sharp X68000" },
  { value: "xbox", label: "Microsoft Xbox" },
  { value: "xbox360", label: "Microsoft Xbox 360" },
  { value: "xboxone", label: "Microsoft Xbox One" },
  { value: "zmachine", label: "Infocom Z-machine" },
  { value: "zx81", label: "Sinclair ZX81" },
  { value: "zxnext", label: "Sinclair ZX Spectrum Next" },
  { value: "zxspectrum", label: "Sinclair ZX Spectrum" },
];

/**
 * Media filter options for filtering games by missing media types
 */
export const MEDIA_FILTER_OPTIONS = [
  {
    key: "all",
    label: "All Games",
    description: "Show all games regardless of media status",
  },
  {
    key: "missing-covers",
    label: "Missing Covers",
    description: "Show games that don't have cover images",
  },
  {
    key: "missing-marquees",
    label: "Missing Marquees/Logos",
    description: "Show games that don't have marquee/logo images",
  },
  {
    key: "missing-screenshots",
    label: "Missing Screenshots",
    description: "Show games that don't have screenshot images",
  },
  {
    key: "missing-titlescreens",
    label: "Missing Title Screens",
    description: "Show games that don't have title screen images",
  },
  {
    key: "missing-3dboxes",
    label: "Missing 3D Boxes",
    description: "Show games that don't have 3D box images",
  },
  {
    key: "missing-backcovers",
    label: "Missing Back Covers",
    description: "Show games that don't have back cover images",
  },
  {
    key: "missing-fanart",
    label: "Missing Fan Art",
    description: "Show games that don't have fan art images",
  },
  {
    key: "missing-physicalmedia",
    label: "Missing Physical Media",
    description: "Show games that don't have physical media images",
  },
  {
    key: "missing-videos",
    label: "Missing Videos",
    description: "Show games that don't have video files",
  },
  {
    key: "missing-any",
    label: "Missing Any Media",
    description: "Show games that are missing at least one media type",
  },
  {
    key: "complete",
    label: "Complete Media Sets",
    description: "Show games that have all media types available",
  },
];

/**
 * Quick filter options for one-click filtering shortcuts
 */
export const QUICK_FILTER_OPTIONS = [
  {
    key: "missing-any",
    label: "Missing Media",
    description: "Games missing at least one media type",
  },
  {
    key: "complete",
    label: "Complete",
    description: "Games with all media types",
  },
  {
    key: "has-videos",
    label: "Has Videos",
    description: "Games with video files",
  },
  {
    key: "missing-videos",
    label: "No Videos",
    description: "Games without video files",
  },
  {
    key: "missing-covers",
    label: "No Covers",
    description: "Games without cover images",
  },
  {
    key: "missing-marquees",
    label: "No Marquees",
    description: "Games without marquee/logo images",
  },
  {
    key: "missing-screenshots",
    label: "No Screenshots",
    description: "Games without screenshot images",
  },
  {
    key: "missing-titlescreens",
    label: "No Title Screens",
    description: "Games without title screen images",
  },
  {
    key: "missing-3dboxes",
    label: "No 3D Boxes",
    description: "Games without 3D box images",
  },
  {
    key: "missing-backcovers",
    label: "No Back Covers",
    description: "Games without back cover images",
  },
  {
    key: "missing-fanart",
    label: "No Fan Art",
    description: "Games without fan art images",
  },
  {
    key: "missing-physicalmedia",
    label: "No Physical Media",
    description: "Games without physical media images",
  },
];
